name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Download dependencies # <-- New step
        run: |
          go mod tidy
          go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Download dependencies # <-- New step
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v -cover ./...
